params:
  - mlflow.use_mlflow
  - mlflow.record_platform
  - mlflow.dagshub_url
  - mlflow.local_url
  - mlflow.experiment_name
  - data_path.raw
  - data_path.train
  - data_path.test

stages:
  build_dataset:
    cmd: uv run src/build_dataset.py ${data_path.raw}
    deps:
      - src/build_dataset.py
      - ${data_path.raw}
    params:
      - build_dataset.test_size
      - build_dataset.random_state
    outs:
      - result/log/build_dataset.log
      - data/train/raw
      - data/test/raw
  categorical_binary:
    cmd: uv run src/categorical_binary.py
    deps:
      - src/categorical_binary.py
      - data/train/raw
      - data/test/raw
    outs:
      - result/log/categorical_binary.log
      - data/train/binary
      - data/test/binary
  train:
    cmd: uv run src/train.py ${data_path.train}
    deps:
      - src/train.py
      - ${data_path.train}
    params:
      - train.max_depth
    outs:
      - result/log/train.log
      - model/improved_c45_model.joblib
  evaluate:
    cmd: uv run src/evaluate.py ${data_path.test}
    deps:
      - src/evaluate.py
      - model/improved_c45_model.joblib
      - ${data_path.test}
    outs:
      - result/log/evaluate.log
  
