params:
  - mlflow.use_mlflow
  - mlflow.record_platform
  - mlflow.dagshub_url
  - mlflow.local_url
  - mlflow.experiment_name
  - data_path.raw
  - data_path.train
  - data_path.test

stages:
  build_dataset:
    cmd: uv run src/build_dataset.py ${data_path.raw}
    deps:
      - src/build_dataset.py
      - ${data_path.raw}
    params:
      - build_dataset.test_size
      - build_dataset.random_state
    outs:
      - result/log/build_dataset.log
      - data/train/raw
      - data/test/raw
  categorical_binary:
    cmd: uv run src/categorical_binary.py
    deps:
      - src/categorical_binary.py
      - data/train/raw
      - data/test/raw
    outs:
      - result/log/categorical_binary.log
      - data/train/binary
      - data/test/binary
  sampling:
    cmd: uv run src/sampling.py
    deps:
      - src/sampling.py
      - data/train/sampled_binary
      - data/train/sampled_raw
    params:
      - sampling.method.type
      - sampling.method.name
      - sampling.method.limit_place
    outs:
      - result/log/sampling.log
  train:
    cmd: uv run src/train.py ${data_path.train}
    deps:
      - src/train.py
      - ${data_path.train}
    params:
      - data_path.train
      - train.max_depth
    outs:
      - result/log/train.log
      - models/improved_c45_model.joblib
  evaluate:
    cmd: uv run src/evaluate.py ${data_path.test}
    deps:
      - src/evaluate.py
      - models/improved_c45_model.joblib
      - ${data_path.test}
    params:
      - data_path.test
    outs:
      - result/log/evaluate.log
  train_vector_drl:
    cmd: uv run src/train_vector_drl.py
    deps:
      - src/train_vector_drl.py
      - data/train/binary
      - data/test/binary
    params:
      - data_path.train
      - data_path.test
    outs:
      - result/log/train_vector_drl.log
      - models/policy_net.pth
      - models/target_net.pth
  evaluate_vector_drl:
    cmd: uv run src/evaluate_vector_drl.py
    deps:
      - src/evaluate_vector_drl.py
      - models/policy_net.pth
      - models/target_net.pth
    params:
      - data_path.train
      - data_path.test
    outs:
      - result/log/evaluate_vector_drl.log
