params:
  - mlflow.tracking_uri
  - mlflow.experiment_name

stages:
  build_dataset:
    cmd: uv run src/build_dataset.py data/${dataset_name}
    deps:
      - src/build_dataset.py
      - data/${dataset_name}
    outs:
      - log/build_dataset.log
      - data/train/raw
      - data/test/raw
    params:
      - dataset_name
  categorical_binary:
    cmd: uv run src/categorical_binary.py
    deps:
      - src/categorical_binary.py
      - data/train/raw
      - data/test/raw
    outs:
      - log/categorical_binary.log
      - data/train/binary
      - data/test/binary
  train:
    cmd: uv run src/train.py ${train.data_path}
    deps:
      - src/train.py
      - ${train.data_path}
    params:
      - train.data_path
    outs:
      - log/train.log
      - model/improved_c45_model.joblib
  evaluate:
    cmd: uv run src/evaluate.py ${evaluate.data_path}
    deps:
      - src/evaluate.py
      - model/improved_c45_model.joblib
      - ${evaluate.data_path}
    params:
      - evaluate.data_path
    outs:
      - log/evaluate.log
  train_drl:
    cmd: uv run src/train_drl.py ${train.data_path}
    deps:
      - src/train_drl.py
      - ${train.data_path}
    params:
      - train.data_path
      - train_drl.protocol_dim
      - train_drl.port_dim
      - train_drl.update_target_steps
      - train_drl.batch_size
      - train_drl.gamma
      - train_drl.eps_start
      - train_drl.eps_end
      - train_drl.eps_decay
      - train_drl.tau
      - train_drl.lr
      - train_drl.memory_size
      - train_drl.n_episodes
      - train_drl.max_data_length
      - train_drl.include_category
    outs:
      - log/train_drl.log
      - log/train_result.log
      - model/drl_model.pth
  evaluate_drl:
    cmd: uv run src/evaluate_drl.py ${evaluate.data_path}
    deps:
      - src/evaluate_drl.py
      - model/drl_model.pth
      - ${evaluate.data_path}
    params:
      - evaluate.data_path
      - evaluate.plot
      - evaluate_drl.include_category
    outs:
      - log/evaluate_drl.log
      - evaluate/plots
