dataset_name: CICIDS2017_improved

mlflow:
  tracking_uri: https://dagshub.com/liverHawk/research_data_drl.mlflow
  experiment_name: toshi_pro
  use_azure: False

build_dataset:
  test_size: 0.3
  random_state: 42

categorical_binary:
  binary: True

train:
  data_path: data/train/raw
  model_type: RandomForest

evaluate:
  data_path: data/test/raw
  plot: True

train_drl:
  protocol_dim: 8
  port_dim: 32
# data_path : binary -> include_category: False
  include_category: True

  update_target_steps: 200
  batch_size: 512
  gamma: 0.99
  eps_start: 0.9
  eps_end: 0.05
  eps_decay: 1000000
  tau: 0.005
  lr: 0.001
  memory_size: 100000
  n_episodes: 100
  sample_size: 10000

evaluate_drl:
  include_category: True