cuda_device_number: 1

data_path:
  raw: data/CICIDS2017_improved
  train: data/train/sampled_raw
  test: data/test/raw

mlflow:
  use_mlflow: true
  record_platform: local   # "azure", "dagshub", "local"

  dagshub_url: https://dagshub.com/liverHawk/research_data_drl.mlflow
  local_url: http://127.0.0.1:5000

  experiment_name: gpu

build_dataset:
  test_size: 0.2
  random_state: 42
sampling:
  use_sampling: true
  method:
    type: over   # "over", "under"
    name: smote
    limit_place: 3
train:
  max_depth: 5


# sampling.method.name
# over: "random", "smote", "adasyn", "borderline_smote", "kmeans_smote", "svmsmote"
# under: "random", "cluster_centroid", "edited_nearest_neighbors", "repeated_edited_nearest_neighbors", "all_knn", "instance_hardness_threshold", "near_miss", "neighbourhood_cleaning_rule", "one_sided_selection", "tomek_links"
