data_path:
  raw: data/CICIDS2017_improved
  train: data/train/raw
  test: data/test/raw

mlflow:
  use_mlflow: True
  record_platform: "local" # "azure", "dagshub", "local"

  dagshub_url: "https://dagshub.com/liverHawk/research_data_drl.mlflow"
  local_url: "http://127.0.0.1:5000"

  experiment_name: desktop_linux

build_dataset:
  test_size: 0.2
  random_state: 42
train:
  max_depth: 3