dataset_name: CICIDS2017_improved

mlflow:
  tracking_uri: http://127.0.0.1:5000
  experiment_name: research_dataset

build_dataset:
  test_size: 0.3
  random_state: 42

categorical_binary:
  binary: true

train:
  data_path: data/train/raw
  model_type: RandomForest

evaluate:
  data_path: data/test/raw
  plot: true

train_drl:
  protocol_dim: 8
  port_dim: 32

  include_category: true

  update_target_steps: 200
  batch_size: 1024
  gamma: 0.99
  eps_start: 0.9
  eps_end: 0.05
  eps_decay: 10000
  tau: 0.005
  lr: 0.001
  memory_size: 100000
  n_episodes: 10
  sample_size: 10000
